#!/usr/bin/python3
import os

currentDir = os.getcwd()
print(currentDir)
print(os.path.exists(15))
os.makedirs('15')


# if os.path.exists('bac') == False :
#     os.makedirs('bac')
# os.chdir('bac')
